### PR TITLE
commiting a upload file feature to detect an image

### PR DESCRIPTION
**Pull request by vallabhdev**

### CODE REVIEW

**Review by AkhilAkoliya — COMMENTED** [review]
Good to go ahead.

**Review by eptuabd20 — APPROVED** [review]
Good to go

**Review by JinalBarot — COMMENTED** [review]
Please explain you have deleted app.py

**Comment by vallabhdev** [comment]
> Please explain you have deleted app.py

We need to have only one app.py file which will be the entry point of our program. We already have this file under /src/ui directory. so removed this.

**Comment by JinalBarot** [comment]
> We need to have only one app.py file which will be the entry point of our program. We already have this file under /src/ui directory. so removed this.

Okay, Prateek. Thank you for the explanation.

**Comment by JinalBarot** [comment]
Kindly add readme file so that everyone can get insights for the project.

**Comment by vallabhdev** [comment]
> 71b03c3

Yes, this has been added in the readme file.. Will keep updating it going forward.

**Comment by JinalBarot** [comment]
> 

Okay. Thanks

**Review by JinalBarot — APPROVED** [review]
Reviewed the changes and approved

**Pull request merged**
